SELECT EMPLOYEE_ID,
CASE WHEN COUNT(*) = 1 THEN '일반 사원'
     WHEN COUNT(*) = 2 THEN '우수 사원'
     WHEN COUNT(*) = 3 THEN '우수 사원'
     ELSE '최우수 사원'
     END AS 분류상태,
     COUNT(*) as COUNT
from SELLINGS
GROUP BY EMPLOYEE_ID
ORDER BY EMPLOYEE_ID;